"""crear tabla historial_interacciones

Revision ID: 087a5db06f41
Revises: 210e97a1309a
Create Date: 2026-07-05 18:51:15.280069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '087a5db06f41'
down_revision: Union[str, Sequence[str], None] = '210e97a1309a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_interacciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recurso_id', sa.String(), nullable=True),
    sa.Column('tipo_evento', sa.String(), nullable=False),
    sa.Column('metadata_extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_interacciones_user_id'), 'historial_interacciones', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_historial_interacciones_user_id'), table_name='historial_interacciones')
    op.drop_table('historial_interacciones')
    # ### end Alembic commands ###
