"""hacer url_descarga opcional en recursos_educativos

Revision ID: 1edaf62d640c
Revises: 5bb55dd51a9a
Create Date: 2026-07-15 18:43:52.949659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1edaf62d640c'
down_revision: Union[str, Sequence[str], None] = '5bb55dd51a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recursos_educativos', 'url_descarga',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recursos_educativos', 'url_descarga',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
