"""crear tabla recursos_educativos

Revision ID: 210e97a1309a
Revises: 9752999f0e82
Create Date: 2026-07-05 18:32:27.803329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210e97a1309a'
down_revision: Union[str, Sequence[str], None] = '9752999f0e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recursos_educativos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('tipo_formato', sa.String(), nullable=False),
    sa.Column('url_descarga', sa.String(), nullable=False),
    sa.Column('tiene_lengua_senas', sa.Boolean(), nullable=False),
    sa.Column('nivel_dificultad', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recursos_educativos')
    # ### end Alembic commands ###
