"""agregar nombre_completo a usuarios

Revision ID: 2113e6a84a49
Revises: 89bd42526d7e
Create Date: 2026-07-05 19:25:02.124423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2113e6a84a49'
down_revision: Union[str, Sequence[str], None] = '89bd42526d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('nombre_completo', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'nombre_completo')
    # ### end Alembic commands ###
