"""agregar transcripcion y tabla archivos_recurso

Revision ID: 5bb55dd51a9a
Revises: b8dd33337092
Create Date: 2026-07-15 18:32:20.933688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb55dd51a9a'
down_revision: Union[str, Sequence[str], None] = 'b8dd33337092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archivos_recurso',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recurso_id', sa.String(), nullable=False),
    sa.Column('tipo_archivo', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos_educativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archivos_recurso_recurso_id'), 'archivos_recurso', ['recurso_id'], unique=False)
    op.add_column('recursos_educativos', sa.Column('transcripcion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recursos_educativos', 'transcripcion')
    op.drop_index(op.f('ix_archivos_recurso_recurso_id'), table_name='archivos_recurso')
    op.drop_table('archivos_recurso')
    # ### end Alembic commands ###
