"""crear tabla perfil_aprendiz

Revision ID: 9752999f0e82
Revises: 
Create Date: 2026-07-05 18:06:51.910695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9752999f0e82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfil_aprendiz',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('grado_perdida_auditiva', sa.String(), nullable=False),
    sa.Column('preferencia_comunicativa', sa.String(), nullable=False),
    sa.Column('nivel_lectura', sa.String(), nullable=False),
    sa.Column('requiere_alto_contraste', sa.Boolean(), nullable=False),
    sa.Column('tamano_subtitulos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_aprendiz_user_id'), 'perfil_aprendiz', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_perfil_aprendiz_user_id'), table_name='perfil_aprendiz')
    op.drop_table('perfil_aprendiz')
    # ### end Alembic commands ###
