"""agregar verificacion de email y recuperacion de password

Revision ID: b8dd33337092
Revises: 5a09558aa399
Create Date: 2026-07-11 16:36:55.852747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8dd33337092'
down_revision: Union[str, Sequence[str], None] = '5a09558aa399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_verificacion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_verificacion_user_id'), 'codigos_verificacion', ['user_id'], unique=False)
    op.add_column('usuarios', sa.Column('email_verificado', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'email_verificado')
    op.drop_index(op.f('ix_codigos_verificacion_user_id'), table_name='codigos_verificacion')
    op.drop_table('codigos_verificacion')
    # ### end Alembic commands ###
