"""agregar quiz diagnostico

Revision ID: c1715cd741d4
Revises: 1edaf62d640c
Create Date: 2026-07-31 06:10:25.857092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1715cd741d4'
down_revision: Union[str, Sequence[str], None] = '1edaf62d640c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preguntas_quiz',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recurso_id', sa.String(), nullable=False),
    sa.Column('enunciado', sa.String(), nullable=False),
    sa.Column('opciones', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('indice_correcta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos_educativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preguntas_quiz_recurso_id'), 'preguntas_quiz', ['recurso_id'], unique=False)
    op.create_table('resultados_quiz_diagnostico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recursos_dominados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resultados_quiz_diagnostico_user_id'), 'resultados_quiz_diagnostico', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resultados_quiz_diagnostico_user_id'), table_name='resultados_quiz_diagnostico')
    op.drop_table('resultados_quiz_diagnostico')
    op.drop_index(op.f('ix_preguntas_quiz_recurso_id'), table_name='preguntas_quiz')
    op.drop_table('preguntas_quiz')
    # ### end Alembic commands ###
